JavaScript: true
engines:
  eslint:
    enabled: true
    checks:
      complexity:
        enabled: false
  nodesecurity:
    enabled: true
  markdownlint:
    enabled: true

ratings:
   paths:
   - "**.js"
   - "**.md"
